name: Update Domains
on:
  schedule:
    - cron: "0 */6 * * *"  # Esegui ogni 6 ore
  workflow_dispatch:      # Permette di avviare manualmente il workflow
  push:
    branches:    
      - '**'         # matches every branch 

jobs:
  update-domains:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: List files for debugging
      run: ls -la

    - name: Update domains in config.json
      run: |
        cd ${{ github.workspace }}
        python update_domains.py

    - name: Commit and push changes (if any)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add config.json
        if ! git diff --cached --quiet; then
          git commit -m "Update config.json [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
